# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_packages: pkgdown
addons:
  apt:
    packages:
    - libharfbuzz-dev
    - libfribidi-dev

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
env:
  global:
    - MAKEFLAGS="-j 2"
before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
